services:
  powerdown-controller:
    image: ghcr.io/nooklabsuk/octopus-power-down-powerwall-controller:v0.3.0
    container_name: powerdown-controller
    env_file:
      - .env
    volumes:
      - ./state:/state
      - ./tariff/teslemetry-normal-tariff.json:/tariff/teslemetry-normal-tariff.json:ro
    restart: unless-stopped
