services:
  powerdown-controller:
    image: ghcr.io/nooklabsuk/octopus-power-down-powerwall-controller:v0.4.0
    container_name: powerdown-controller
    env_file:
      - .env
    volumes:
      - ./state:/state
      - ./tariff:/tariff:ro
    restart: unless-stopped
